FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY leaderless/go.mod ./
RUN go mod download
COPY leaderless/*.go ./
RUN CGO_ENABLED=0 go build -o kvnode .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/kvnode .
EXPOSE 8080
CMD ["./kvnode"]